# errata:
# - sudo/dist/group are set so as to get Blue Box VMs, necessary for [loopback]
#   IPv6 support

sudo: required
dist: trusty

os: linux
language: generic

services:
  - docker

cache:
  ccache: true
  directories:
    - $HOME/cache

env:
  global:
    # DOCKER_HUB_USER
    - secure: "yKd3kwdCZVQ+szHz/JJre7oIhNhHv3sh2Zi8jdLh0MuMvHHGVfF10/BWoQiR5SiOyXfxtTdOMp8eX/4JFeXSnOUzPmoSZLE+rROPyyQ+FjvQkxXUpROIx2xmRDfcA3CsMXb+rzezcWEZ0byU5ZaT8xMu0We+6nCRJvJCtycgckWuI0mlxJGfgJP1ZofLpkBYu7sn6e1J/G8qZrzYZM1dlJJK1HhSWQ7PTo7PKjkXTXfYmNLWkVnAOXcs1gHpGecaf+kABht78WZheMvuIPrk4fOU3gBaXz2Ol2F1bqzy2g27uB0hOav+FGvRj0W2pFgr+AouNOabNzAbN2bahY75PB6CAiJAB1WpuQMTiVnWVVjscejupPaX4hB2xKyVPdXnk0DCgXNLNDv0P/WSdFxg6wjTFVuN3aSKave+5+Iek6HoXluRCiXOY6sHTsuaAzFGTIVmHGJQUOhK3e3eR1A8pLXQsN83mT+lBWfpthb0lui2pqWeXLIkl8nL+htyoC2ZqlXafUtSiBsnE1ZhbClSfIl1t6jFx3UFIo1bQHQYC1zGAFINhcSiitWVfmceeCArHx+QH+SCI00oyqFHLdBKhhUTT6OsA1wL8FrT7gyEY/KigGHlpNQRVhVRIP+FbwLEdHG4/2O1l7rKdO/6dCzhCp0EpCn3ZNaq5sLHbbm2R3g="
    # DOCKER_HUB_PASSWORD
    - secure: "HIf+yxHDZfkZ9KGJIz6TtYSk1b1gQrtgzEkjNFybl6dQ17e3il9OitFPq38qnrv2ySuuWIJZbVzU8yOJeS9eL0Gq3UCaxFoH94DUnYd0yq1IbZdPdWjpUK+xBIyu/Vf/hRz/hxoGVN1JGfNtfksIKAtloxKTNxb0AD5Bn8GLfsxo2tQtCCINuzy8vZFjnxYM6K1Az3x6p5ov2tLWwf+JVIUgxeyAktAktX0W4o1ioiZugm0P/S0oJre/0NLWLocu6f9mpKU2QI9e5oPDRipS6+S/paBL6eDNjMFVDC2EdIjS/hsut0KpEpfcbE9Jat299/Rc5W1LIkNvtgLqq4Ah5iXBZoYoJYyXyQUJ1HUKowZ2AstbaXeK/wVtpm+LJNghsUku17k1zdh+N7dZnJPZ5WpMDnmAkaDWIwFXKsM7gzDI1vgmYkXnEr6wAEOGZxNF/6IqsFwoPRqVJPUlroCWH8xCJb+ayG7MsakOMi3KcLpwXmzHUM7t5hs7ixdSmXp3XVz8t040gxce34tGRIo028ckosWxa/w5mJVHQ/2lninXPIHXoeJKoQLWGsQXh5N7PTExZd6arpIFha2XZv1eoOWYx1Am1R258WB/Q2+hGcMJ+nHorQaFBL/vmCzoMLsj8AYvhKDnQjkmg2Ab7n5sBaECXQjv+hmmPuIhx4V/etM="
    - DOCKER_BUILD=false

stages:
  - build depends
  - build src
  - run tests
  - build docker

builddepends: &builddepends
  stage: build depends
  script:
    - $DOCKER_RUN_IN_BUILDER ./ci/build_depends.sh

buildsrc: &buildsrc
  stage: build src
  script:
    - $DOCKER_RUN_IN_BUILDER ./ci/build_depends.sh
    - $DOCKER_RUN_IN_BUILDER ./ci/build_src.sh

runtests: &runtests
  stage: run tests
  script:
    - $DOCKER_RUN_IN_BUILDER ./ci/build_depends.sh
    - $DOCKER_RUN_IN_BUILDER ./ci/build_src.sh
    - $DOCKER_RUN_IN_BUILDER ./ci/test_unittests.sh
    - $DOCKER_RUN_IN_BUILDER ./ci/test_integrationtests.sh --jobs=3

builddocker: &builddocker
  stage: build docker
  script:
    # no need to run tests again here
    - if [ "$DOCKER_BUILD" = "true" ]; then $DOCKER_RUN_IN_BUILDER ./ci/build_depends.sh && $DOCKER_RUN_IN_BUILDER ./ci/build_src.sh && BUILD_DIR=build-ci/poliscore-$BUILD_TARGET ./docker/build-docker.sh; fi

jobs:
  include:
    # build depends
    - <<: *builddepends
      env: BUILD_TARGET=arm-linux
    - <<: *builddepends
      env: BUILD_TARGET=win32
    - <<: *builddepends
      env: BUILD_TARGET=win64
    - <<: *builddepends
      env: BUILD_TARGET=linux32
    - <<: *builddepends
      env: BUILD_TARGET=linux64_release DOCKER_BUILD=true
    - <<: *builddepends
      env: BUILD_TARGET=mac
    # build source
    - <<: *buildsrc
      env: BUILD_TARGET=arm-linux
    - <<: *buildsrc
      env: BUILD_TARGET=win32
    - <<: *buildsrc
      env: BUILD_TARGET=win64
    - <<: *buildsrc
      env: BUILD_TARGET=linux32
    - <<: *buildsrc
      env: BUILD_TARGET=linux64_release DOCKER_BUILD=true
    - <<: *buildsrc
      env: BUILD_TARGET=mac
    # run tests (no tests for arm-linux and mac)
    - <<: *runtests
      env: BUILD_TARGET=win32
    - <<: *runtests
      env: BUILD_TARGET=win64
    - <<: *runtests
      env: BUILD_TARGET=linux32
    - <<: *runtests
      env: BUILD_TARGET=linux64_release DOCKER_BUILD=true
    # build docker
    - <<: *builddocker
      env: BUILD_TARGET=linux64_release DOCKER_BUILD=true

before_cache:
  # Save builder image
  - docker save polis-builder-$BUILD_TARGET-$TRAVIS_JOB_NUMBER $(docker history -q polis-builder-$BUILD_TARGET-$TRAVIS_JOB_NUMBER | grep -v \<missing\>) | gzip -2 > $HOME/cache/docker/polis-builder-$BUILD_TARGET.tar.gz

before_install:
  - travis_retry travis_apt_get_update
  - travis_retry sudo apt-get -yq --no-install-suggests --no-install-recommends install docker-ce realpath

install:
  # Our scripts try to be Travis agnostic
  - export PULL_REQUEST="$TRAVIS_PULL_REQUEST"
  - export JOB_NUMBER="$TRAVIS_JOB_NUMBER"
  - export HOST_SRC_DIR=$TRAVIS_BUILD_DIR
  - export HOST_CACHE_DIR=$HOME/cache
  - export TRAVIS_COMMIT_LOG=`git log --format=fuller -1`
  - source ./ci/matrix.sh
  - mkdir -p $HOST_CACHE_DIR/docker && mkdir -p $HOST_CACHE_DIR/ccache && mkdir -p $HOST_CACHE_DIR/depends && mkdir -p $HOST_CACHE_DIR/sdk-sources
  # Keep this as it makes caching related debugging easier
  - ls -lah $HOST_CACHE_DIR && ls -lah $HOST_CACHE_DIR/depends && ls -lah $HOST_CACHE_DIR/ccache && ls -lah $HOST_CACHE_DIR/docker
  # Load cached builder image
  - if [ -f $HOST_CACHE_DIR/docker/polis-builder-$BUILD_TARGET.tar.gz ]; then zcat $HOST_CACHE_DIR/docker/polis-builder-$BUILD_TARGET.tar.gz | docker load || true; fi
  - travis_retry docker pull ubuntu:bionic
  - travis_retry docker build -t $BUILDER_IMAGE_NAME --build-arg=USER_ID=$UID --build-arg=GROUP_ID=$UID --build-arg=BUILD_TARGET=$BUILD_TARGET -f ci/Dockerfile.builder ci
before_script:
  # Make sure stdout is in blocking mode. Otherwise builds will fail due to large writes to stdout
  # See https://github.com/travis-ci/travis-ci/issues/4704. If this gets fixed, this line can also be removed.
  - python3 -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
  # Build docker image only for develop branch of the main repo
  - if [ "$TRAVIS_REPO_SLUG" != "polispay/polis" -o "$TRAVIS_BRANCH" != "develop" -o "$TRAVIS_PULL_REQUEST" != "false" ]; then export DOCKER_BUILD="false"; echo DOCKER_BUILD=$DOCKER_BUILD; fi
after_script:
  - echo $TRAVIS_COMMIT_RANGE
  - echo $TRAVIS_COMMIT_LOG
after_success:
  - if [ "$DOCKER_BUILD" = "true" ]; then docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD && ./docker/push-docker.sh; fi